### ISSUE TITLE
Rename fake-factory to Faker

### ISSUE THREAD

**Issue by ArturFormella** [guedes/faker_fdw#1]
Hello, running query:
```
CREATE SERVER faker_srv8
 FOREIGN DATA WRAPPER multicorn
 OPTIONS (wrapper 'faker_fdw.FakerForeignDataWrapper');
```
I have an exception:
```
SQL error:
ERROR:  Error in python: ImportError
DETAIL:  The ``fake-factory`` package is now called ``Faker``.
Please update your requirements.
```
The "fake-factory" package name is depreciated.
Look also at this:
https://github.com/FactoryBoy/factory_boy/issues/334

**Comment by guedes** [comment]
Hum... My fault, I've fixed that as you can see [here](https://github.com/guedes/faker_fdw/blob/v0.1.1/faker_fdw/__init__.py#L25) but didn't fixed the README :( I'm changing that! Thanks for pointing it.

**Comment by guedes** [comment]
I've fixed the `README`.

To install you should change the version from v0.1.0 to v0.1.1:

`sudo pip install http://github.com/guedes/faker_fdw/archive/v0.1.1.zip`

Regards!
